apiVersion: apps/v1
kind: Deployment
metadata:
  name: watsai-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: watsai
    template:
      metadata:
        labels:
          app: watsai
        spec:
          containers:
          - name: watsai-container
            image: sandramsc/watsai:latest
            ports:
            - containerPort: 8501
