apiVersion: v1
kind: Service
metadata:
  name: watsai-service
spec:
  selector:
    app: watsai
  ports:
    - protocol: TCP
      ports: 80
      targetPort: 8501
      nodePOrt: 30007
  type: NodePort
